version: '3'
services:

    mysql:
      image: alpine-mariadb-tzparis
      build: .
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tmpdb
        MYSQL_USER: tmpdb
        MYSQL_PASSWORD: tmpdb
      ports:
        - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
        - ./local/mysql/my.cnf:/etc/my.cnf
        - ./local/mysql/my.cnf.d:/etc/my.cnf.d
      restart: always

# NB: Be careful with dates (UTC by default).
